# Timeout for commands (ms)
command_timeout = 1000

format = """$all"""
right_format = """
$cmd_duration\
$jobs\
$battery\
$aws\
$gcloud\
$azure\
$kubernetes\
$terraform\
$nix_shell\
$direnv\
$username\
$hostname\
$os\
$time"""

[docker_context]
disabled = true

[gcloud]
disabled = true

[status]
disabled = false

[time]
disabled = false

[os]
disabled = false

[git_status]
conflicted = "✘"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
